CREATE TABLE usuarios (
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(30) NOT NULL,
    email VARCHAR(50) NOT NULL
);

ALTER TABLE usuarios
ADD idade INT(3) NOT NULL,
ADD rg VARCHAR(20) NOT NULL;
